"""
Utility functions for plotting used throughout fluxmax.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from beartype import beartype
from jaxtyping import Float, Array, jaxtyped

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from beartype import beartype
from jaxtyping import Float, Array, jaxtyped


@jaxtyped(typechecker=beartype)
def plot_square_bz_points(
    in_plane_wavevector: Float[Array, "... 2"],
    pitch: float,
) -> Figure:
    """Plot the in-plane wavevectors within the first Brillouin zone for a square lattice.

    Parameters
    ----------
    in_plane_wavevector : Float[Array, "... 2"]
        The in-plane wavevectors generated by fmmax. The final dimension must 
        be 2, representing the kx and ky components. Leading dimensions represent 
        the grid points.
    pitch : float
        The real-space periodicity (lattice constant) of the square unit cell.

    Returns
    -------
    Figure
        The matplotlib figure object containing the Brillouin zone plot.

    Raises
    ------
    ValueError
        If the pitch is less than or equal to zero.

    Notes
    -----
    This function assumes a square lattice geometry where the first
    Brillouin zone is mathematically bounded by [-pi/pitch, pi/pitch] 
    in both the kx and ky directions. It does not generalize to other
    lattices.
    """
    if pitch <= 0:
        raise ValueError("Lattice pitch must be strictly positive.")

    # Isolate kx and ky from the final axis and flatten spatial dimensions
    kx = np.asarray(in_plane_wavevector[..., 0]).flatten()
    ky = np.asarray(in_plane_wavevector[..., 1]).flatten()

    pi_over_a = np.pi / pitch

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(kx, ky, c='blue', marker='o', s=15, label='Sampled Wavevectors')

    # Construct the square First Brillouin Zone boundaries
    ax.axhline(pi_over_a, color='black', linestyle='--', alpha=0.5, label='BZ Boundary')
    ax.axhline(-pi_over_a, color='black', linestyle='--', alpha=0.5)
    ax.axvline(pi_over_a, color='black', linestyle='--', alpha=0.5)
    ax.axvline(-pi_over_a, color='black', linestyle='--', alpha=0.5)

    ax.set_xlabel(r'$k_x$')
    ax.set_ylabel(r'$k_y$')
    ax.set_title('Reciprocal Space Sampling (Square Lattice)')

    limit = 1.2 * pi_over_a
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.grid(True, alpha=0.3)
    ax.set_aspect('equal', adjustable='box')

    handles, labels = ax.get_legend_handles_labels()
    by_label = dict(zip(labels, handles))
    ax.legend(by_label.values(), by_label.keys())

    return fig